/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.testing.iotest;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int btnRead=0x7f050003;
        public static final int btnWrite=0x7f050002;
        public static final int root_layout=0x7f050000;
        public static final int textInput=0x7f050001;
        public static final int textOutput=0x7f050005;
        public static final int view_as_html=0x7f050004;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
